#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

class Euler2

	
	def fibonacci
		#create an addition of the first two terms and a total.
	  first, second, total = 1,2,0
	  # Create loop with the second/current number being less than 4 million.
	  while second < 4000000
	  	#The second will equal and add onto the total only if it's even.
	    total += second if second.even?
	    #The first will add on to second and if even add to the sequence 
	    # and will add to the previous (second).
	    first, second = second, first + second
	  end
	  puts total
	end



end

d = Euler2.new

d.fibonacci